windows_install_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  install_script: |-
    choco install -y nsis
    choco install -y cmake --version 3.14
    set PATH="C:\Program Files (x86)\CMake 3.14\bin\";%PATH%

test_task_template: &TEST_TASK_TEMPLATE
  only_if: $CIRRUS_TAG == ''
  test_script: |-
    cmake .
    cmake --build .

windows_test_task:
  <<: *TEST_TASK_TEMPLATE
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  depends_on:
    - windows_install

mac_test_task:
  <<: *TEST_TASK_TEMPLATE
  osx_instance:
    image: mojave-xcode-10.2
