language: cpp
dist: xenial
compiler:
- gcc
os:
- linux
- osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install cmake;
    fi
script:
  - cmake .
  - cmake --build . -- -j3
  - cpack .