language: cpp
dist: xenial
compiler:
- gcc
os:
- linux
- osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install cmake;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -qq;
      sudo apt-get install -qq rpm;
    fi
script:
  - cmake .
  - cmake --build . -- -j3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cpack -G DEB .;
      cpack -G RPM .;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cpack -G DragNDrop .;
    fi