version: 0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

image:
  - Visual Studio 2019
  - Visual Studio 2017

clone_folder: c:\projects\railshell

init:
  - cmd: |-
      # Build Generator
      set arch=
      if "%arch%"=="Win64" ( set arch= Win64)
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
      
      # Dependencies
      choco install nsis -pre
  - ps: |-
      # Version
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      } else {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

before_build:
  - cmd: |-
      # Generate Build Files
      cmake . -G %generator%

build_script:
  - ps: |-
      # Build and Package the App
      cpack -G NSIS .

test_script:
  - cmd: |-
      # Test if it builds
      cmake .
      cmake --build .


artifacts:
- path: '*.exe'
  name: Installer

deploy:
- provider: GitHub
  auth_token:
    secure: JYqExHLUme29xJ0gLyh3sg42sV5kXQDL0JushVcUywQxDN1HsNdMUO73o2HHn56+
  artifact: Installer
  force_update: true