version: 0.{build}

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true

image:
  - Visual Studio 2019
  - Visual Studio 2017

clone_folder: c:\projects\railshell

init:
  - cmd: |-
      set arch=
      if "%arch%"=="Win64" ( set arch= Win64)
      echo %arch%
      echo %APPVEYOR_BUILD_WORKER_IMAGE%
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 15 2019%arch%" )
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
      echo %generator%
  - ps: |-
      choco install nsis -pre
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      } else {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

before_build:
- cmd: >-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%

build:
  project: c:\projects\railshell\build\template.sln
  verbosity: minimal
  parallel: true

after_build:
  - ps: >-
      cpack -G NSIS .

test_script:
- sh: >-
    chmod +x scripts/build.sh
    ./scripts/build.sh windows

artifacts:
- path: '*.exe'
  name: Installer

deploy:
- provider: GitHub
  auth_token:
    secure: JYqExHLUme29xJ0gLyh3sg42sV5kXQDL0JushVcUywQxDN1HsNdMUO73o2HHn56+
  artifact: Installer
  force_update: true